/* parser.tab.h — token definitions (normally generated by bison -d parser.y) */
#ifndef PARSER_TAB_H
#define PARSER_TAB_H

#include "ast.h"

typedef union YYSTYPE {
    int      ival;
    float    fval;
    char    *sval;
    ASTNode *node;
    DataType dtype;
} YYSTYPE;

extern YYSTYPE yylval;

/* Token codes */
enum yytokentype {
    INT_LIT    = 258,
    FLOAT_LIT  = 259,
    STRING_LIT = 260,
    IDENTIFIER = 261,
    LET        = 262,
    PRINT      = 263,
    TYPE_INT   = 264,
    TYPE_FLOAT = 265,
    TYPE_STRING= 266,
    ASSIGN     = 267,
    PLUS       = 268,
    MINUS      = 269,
    STAR       = 270,
    SLASH      = 271,
    LPAREN     = 272,
    RPAREN     = 273,
    SEMICOLON  = 274,
    COMMA      = 275
};

#endif /* PARSER_TAB_H */
